#!/usr/bin/env node
// Build src/lib/price-snapshot.ts: a dated subset of LiteLLM's
// model_prices_and_context_window.json, pinned to one commit.
//
//   node scripts/prices/snapshot.mjs <full commit sha> <commit date, YYYY-MM-DD> < prices.json
//
// Fetch the file at a commit, never at a branch, so the bytes and the version
// name agree:
//   curl -sSo prices.json https://raw.githubusercontent.com/BerriAI/litellm/<sha>/model_prices_and_context_window.json
//
// Why a subset and why on the server. The full file is about 2.8 MB and 4,200
// entries, and it changed 23 times on 2026-09-23 alone. Shipping it inside an
// SDK would freeze a price table into every installed copy. Here it is one
// file the server reads, named by PRICE_VERSION, and every event it prices
// stores that name, so a figure can always be traced to the table it came from.
//
// What is kept. The entries whose litellm_provider is openai, anthropic or
// gemini (Google AI Studio; the "gemini/" prefix is dropped, and Vertex AI
// entries are not kept) in mode chat or responses: the three providers wrap()
// recognises, through the methods it wraps. Of each entry, only the per-token
// fields the pricer reads: input, output, cache read, cache write (5 minute and
// 1 hour), reasoning, audio, each with its long-context tier (_above_<N>k_tokens)
// and service tier (_flex, _priority) variants. Batch rates are dropped: a batch
// job does not go through the methods wrap() measures.
//
// Licence. The file is in the MIT-licensed portion of the LiteLLM repository
// (everything outside enterprise/). The notice is copied into the generated
// file and into THIRD_PARTY_NOTICES.md.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..')
const [sha, date] = process.argv.slice(2)
if (!/^[0-9a-f]{40}$/.test(sha ?? '') || !/^\d{4}-\d{2}-\d{2}$/.test(date ?? '')) {
  console.error('usage: node scripts/prices/snapshot.mjs <40-char commit sha> <YYYY-MM-DD> < prices.json')
  process.exit(2)
}

const PROVIDERS = new Set(['openai', 'anthropic', 'gemini'])
const MODES = new Set(['chat', 'responses'])
const FIELD = /^(input_cost_per_token|output_cost_per_token|cache_read_input_token_cost|cache_creation_input_token_cost|output_cost_per_reasoning_token|input_cost_per_audio_token|output_cost_per_audio_token|cache_read_input_audio_token_cost)(_above_1hr)?(_above_\d+k_tokens)?(_flex|_priority)?$/

// The price file arrives on stdin, so no argument ever names a path to read.
const all = JSON.parse(readFileSync(0, 'utf8'))
const models = {}
let skippedFields = 0
for (const [key, entry] of Object.entries(all)) {
  if (key === 'sample_spec' || !entry || typeof entry !== 'object') continue
  if (!PROVIDERS.has(entry.litellm_provider) || !MODES.has(entry.mode)) continue
  const name = entry.litellm_provider === 'gemini' ? key.replace(/^gemini\//, '') : key
  if (entry.litellm_provider === 'gemini' && name === key) continue // an AI Studio entry always carries the prefix
  const rates = {}
  for (const [f, v] of Object.entries(entry)) {
    if (!FIELD.test(f)) continue
    if (typeof v !== 'number' || !Number.isFinite(v) || v < 0) { skippedFields++; continue }
    // The pricer works in whole picodollars (1e-12 USD) per token, so every
    // rate has to be one exactly. A rate finer than that would be rounded
    // without a word, which is the kind of silent number this file refuses.
    const pico = v * 1e12
    if (Math.abs(pico - Math.round(pico)) > 1e-6) throw new Error(`${key}.${f} = ${v} is not a whole number of picodollars`)
    rates[f] = v
  }
  if (!('input_cost_per_token' in rates) || !('output_cost_per_token' in rates)) continue
  if (models[name]) throw new Error(`two entries for ${name}`)
  models[name] = { provider: entry.litellm_provider, rates }
}

const names = Object.keys(models).sort()
const version = `litellm-${sha.slice(0, 7)}-${date}`
const licence = readFileSync(join(ROOT, 'scripts/prices/LITELLM-LICENSE'), 'utf8').trim()
const body = names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(models[n])},`).join('\n')
const out = `// GENERATED by scripts/prices/snapshot.mjs. Do not edit by hand: regenerate,
// which also moves PRICE_SNAPSHOT.version, the name every priced event stores.
//
// Source: https://github.com/BerriAI/litellm/blob/${sha}/model_prices_and_context_window.json
// (commit ${sha}, ${date}). ${names.length} entries kept: litellm_provider
// openai, anthropic and gemini, mode chat and responses, per-token fields only.
// See the generator's header for exactly what is kept and why.
//
// The source file is in the MIT-licensed portion of the LiteLLM repository.
// Its licence, as published at that commit:
//
${licence.split('\n').map((l) => `// ${l}`.trimEnd()).join('\n')}

export type SnapshotProvider = 'openai' | 'anthropic' | 'gemini'
export type SnapshotModel = { provider: SnapshotProvider; rates: Record<string, number> }

export const PRICE_SNAPSHOT: {
  version: string
  source: { repository: string; path: string; commit: string; date: string }
  models: Record<string, SnapshotModel>
} = {
  version: ${JSON.stringify(version)},
  source: { repository: 'BerriAI/litellm', path: 'model_prices_and_context_window.json', commit: ${JSON.stringify(sha)}, date: ${JSON.stringify(date)} },
  models: {
${body}
  },
}
`
writeFileSync(join(ROOT, 'src/lib/price-snapshot.ts'), out)
console.log(`wrote src/lib/price-snapshot.ts: ${version}, ${names.length} models, ${skippedFields} non-numeric fields skipped`)
