#!/usr/bin/env bash
# Cut the homepage's hero loop out of the 30s brand film and compile it into a
# Buffer module, the same way scripts/og and scripts/photo do, because the
# Dockerfile's runtime stage copies dist/ and nothing else.
#
# WHAT IS CUT, AND WHY IT IS NOT THE WHOLE FILM.
# ~8.5 of the film's 29.8 seconds are a blue analytics dashboard that is not
# AgentBill and not any real product (94.7% AI Model Accuracy, 1.2M Daily API
# Calls, an "AI forecast" paragraph), running before the brand is named at 0:13.
# It is recorded in M-memory/feedback.md as an open defect. A homepage may not
# autoplay invented UI, least of all under a film that says "It won't invent
# anything" nine seconds later.
#
# 16.6 -> 20.4 is the section that IS the product: the console's task counter
# climbing 160 -> 492 of 500, `researcher needs 12` turning red, and the refusal
# body. Its numbers are the same ones heroRefusalBody() renders, so the film and
# the page's own figure cannot disagree.
set -euo pipefail
SRC="${1:?usage: build.sh <path-to-30s-master.mp4>}"
OUT="src/lib/hero-video.ts"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

ffmpeg -v error -y -ss 16.6 -t 3.8 -i "$SRC" -an \
  -vf "scale=1280:-2" -c:v libx264 -profile:v high -crf 26 -preset slow \
  -pix_fmt yuv420p -movflags +faststart "$TMP/loop.mp4"
ffmpeg -v error -y -ss 20.1 -i "$SRC" -frames:v 1 -vf "scale=1280:-2" -q:v 4 "$TMP/poster.jpg"

# An audio stream would make autoplay a browser-policy problem AND ship sound
# nobody asked for. Refuse rather than warn.
if ffprobe -v error -show_entries stream=codec_type -of csv=p=0 "$TMP/loop.mp4" | grep -q audio; then
  echo "FAIL: the loop still carries an audio stream" >&2; exit 1
fi

node -e '
const fs = require("fs")
const mp4 = fs.readFileSync(process.argv[1]).toString("base64")
const jpg = fs.readFileSync(process.argv[2]).toString("base64")
const head = `// The homepage hero loop and its poster frame.
// Generated by scripts/hero-video/build.sh from the 30s brand film, which is
// NOT in this repository. Re-run the script to replace them; do not edit by hand.
//
// The loop is 3.8s of 1280x720 h264 with NO audio stream, cut from 16.6-20.4 of
// the master: the console burning job-142 down to 492 of 500 and refusing the
// call that asks for 12. The master is 3840x2160 and 59.3MB; this is 174KB.
// The first ~11 seconds of the master are an invented dashboard and are
// deliberately absent. See the script header.

`
fs.writeFileSync(process.argv[3],
  head +
  "export const HERO_LOOP_MP4: Buffer = Buffer.from(\n  \x27" + mp4 + "\x27,\n  \x27base64\x27\n)\n\n" +
  "export const HERO_POSTER_JPG: Buffer = Buffer.from(\n  \x27" + jpg + "\x27,\n  \x27base64\x27\n)\n\n" +
  "export const HERO_W = 1280\nexport const HERO_H = 720\n")
' "$TMP/loop.mp4" "$TMP/poster.jpg" "$OUT"

printf "wrote %s (%s)\n" "$OUT" "$(du -h "$OUT" | cut -f1)"
